services:
  postgres:
    image: postgres:17-alpine
    container_name: job_tracker-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always